apiVersion: v1
kind: Pod
metadata:
  name: simulator
  labels:
    app: myapp
  namespace: akka-grpc-projection
spec:
  containers:
    - name: myapp-container
      image: ghcr.io/ceecer1/simulator:116
      imagePullPolicy: "Always"
      resources:
        limits:
          memory: "2Gi"
        requests:
          memory: "2Gi"
          cpu: "1800m"
      command:
        - sh
        - run-many-grpcurl.sh

  imagePullSecrets:
    - name: dockerconfigjson-ghcr-io
  restartPolicy: OnFailure